# Generated by Django 5.0 on 2024-01-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_hover',
            field=models.ImageField(default='product.jpg', upload_to='user_directory_path'),
        ),
    ]
