# Generated by Django 4.2.1 on 2023-11-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='image',
        ),
        migrations.AddField(
            model_name='main',
            name='image_banner',
            field=models.ImageField(null=True, upload_to='banners'),
        ),
    ]
