# Generated by Django 4.2.1 on 2023-11-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_main_image_main_image_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='price',
        ),
    ]
