# Generated by Django 4.2.1 on 2023-11-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_category_product_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_head', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=100)),
                ('main_banner_image', models.ImageField(upload_to='banners')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='products'),
        ),
    ]
