# Generated by Django 5.0 on 2024-01-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_productreview_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'banners'},
        ),
        migrations.AlterModelOptions(
            name='collections',
            options={'verbose_name_plural': 'collections'},
        ),
        migrations.AddField(
            model_name='collections',
            name='type',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
