# Generated by Django 5.0 on 2024-01-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_banner_options_alter_collections_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': 'wishlist'},
        ),
    ]
