# Generated by Django 4.2.6 on 2023-11-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_productimages_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='image',
            new_name='images',
        ),
    ]
