# Generated by Django 4.2.6 on 2023-12-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_image_productimages_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='specifications',
            new_name='designation',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.TextField(blank=True, null=True),
        ),
    ]
