# Generated by Django 4.2.6 on 2023-12-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_review_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Product Reviews'},
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
